name: tests

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install virtualenv from poetry
        uses: 20c/workflows/poetry@v1
      - name: Run linters
        run: |
          poetry run pre-commit run --all-files
  test:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: setup dev environment
        run: touch ./Ctl/dev/.env
      - name: Start the DB
        run: ./Ctl/dev/compose.sh up -d database
      - name: build PeeringDB
        run: ./Ctl/dev/compose.sh build --pull peeringdb
      - name: run tests
        run: ./Ctl/dev/run.sh run_tests
